/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RestaurantRouteImport } from './routes/restaurant'
import { Route as ReservationsRouteImport } from './routes/reservations'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as HousekeepingRouteImport } from './routes/housekeeping'
import { Route as HotelRouteImport } from './routes/hotel'
import { Route as IndexRouteImport } from './routes/index'

const RestaurantRoute = RestaurantRouteImport.update({
  id: '/restaurant',
  path: '/restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsRoute = ReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const HousekeepingRoute = HousekeepingRouteImport.update({
  id: '/housekeeping',
  path: '/housekeeping',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelRoute = HotelRouteImport.update({
  id: '/hotel',
  path: '/hotel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hotel': typeof HotelRoute
  '/housekeeping': typeof HousekeepingRoute
  '/maintenance': typeof MaintenanceRoute
  '/reservations': typeof ReservationsRoute
  '/restaurant': typeof RestaurantRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hotel': typeof HotelRoute
  '/housekeeping': typeof HousekeepingRoute
  '/maintenance': typeof MaintenanceRoute
  '/reservations': typeof ReservationsRoute
  '/restaurant': typeof RestaurantRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hotel': typeof HotelRoute
  '/housekeeping': typeof HousekeepingRoute
  '/maintenance': typeof MaintenanceRoute
  '/reservations': typeof ReservationsRoute
  '/restaurant': typeof RestaurantRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hotel'
    | '/housekeeping'
    | '/maintenance'
    | '/reservations'
    | '/restaurant'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hotel'
    | '/housekeeping'
    | '/maintenance'
    | '/reservations'
    | '/restaurant'
  id:
    | '__root__'
    | '/'
    | '/hotel'
    | '/housekeeping'
    | '/maintenance'
    | '/reservations'
    | '/restaurant'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HotelRoute: typeof HotelRoute
  HousekeepingRoute: typeof HousekeepingRoute
  MaintenanceRoute: typeof MaintenanceRoute
  ReservationsRoute: typeof ReservationsRoute
  RestaurantRoute: typeof RestaurantRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/restaurant': {
      id: '/restaurant'
      path: '/restaurant'
      fullPath: '/restaurant'
      preLoaderRoute: typeof RestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations': {
      id: '/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof ReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/housekeeping': {
      id: '/housekeeping'
      path: '/housekeeping'
      fullPath: '/housekeeping'
      preLoaderRoute: typeof HousekeepingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel': {
      id: '/hotel'
      path: '/hotel'
      fullPath: '/hotel'
      preLoaderRoute: typeof HotelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HotelRoute: HotelRoute,
  HousekeepingRoute: HousekeepingRoute,
  MaintenanceRoute: MaintenanceRoute,
  ReservationsRoute: ReservationsRoute,
  RestaurantRoute: RestaurantRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
