/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RestaurantRouteImport } from './routes/restaurant'
import { Route as ReservationsRouteImport } from './routes/reservations'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as HrmRouteImport } from './routes/hrm'
import { Route as HousekeepingRouteImport } from './routes/housekeeping'
import { Route as HotelRouteImport } from './routes/hotel'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantRoute = RestaurantRouteImport.update({
  id: '/restaurant',
  path: '/restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsRoute = ReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const HrmRoute = HrmRouteImport.update({
  id: '/hrm',
  path: '/hrm',
  getParentRoute: () => rootRouteImport,
} as any)
const HousekeepingRoute = HousekeepingRouteImport.update({
  id: '/housekeeping',
  path: '/housekeeping',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelRoute = HotelRouteImport.update({
  id: '/hotel',
  path: '/hotel',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/billing': typeof BillingRoute
  '/crm': typeof CrmRoute
  '/finance': typeof FinanceRoute
  '/hotel': typeof HotelRoute
  '/housekeeping': typeof HousekeepingRoute
  '/hrm': typeof HrmRoute
  '/inventory': typeof InventoryRoute
  '/maintenance': typeof MaintenanceRoute
  '/reservations': typeof ReservationsRoute
  '/restaurant': typeof RestaurantRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/billing': typeof BillingRoute
  '/crm': typeof CrmRoute
  '/finance': typeof FinanceRoute
  '/hotel': typeof HotelRoute
  '/housekeeping': typeof HousekeepingRoute
  '/hrm': typeof HrmRoute
  '/inventory': typeof InventoryRoute
  '/maintenance': typeof MaintenanceRoute
  '/reservations': typeof ReservationsRoute
  '/restaurant': typeof RestaurantRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/billing': typeof BillingRoute
  '/crm': typeof CrmRoute
  '/finance': typeof FinanceRoute
  '/hotel': typeof HotelRoute
  '/housekeeping': typeof HousekeepingRoute
  '/hrm': typeof HrmRoute
  '/inventory': typeof InventoryRoute
  '/maintenance': typeof MaintenanceRoute
  '/reservations': typeof ReservationsRoute
  '/restaurant': typeof RestaurantRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/billing'
    | '/crm'
    | '/finance'
    | '/hotel'
    | '/housekeeping'
    | '/hrm'
    | '/inventory'
    | '/maintenance'
    | '/reservations'
    | '/restaurant'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analytics'
    | '/billing'
    | '/crm'
    | '/finance'
    | '/hotel'
    | '/housekeeping'
    | '/hrm'
    | '/inventory'
    | '/maintenance'
    | '/reservations'
    | '/restaurant'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/billing'
    | '/crm'
    | '/finance'
    | '/hotel'
    | '/housekeeping'
    | '/hrm'
    | '/inventory'
    | '/maintenance'
    | '/reservations'
    | '/restaurant'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BillingRoute: typeof BillingRoute
  CrmRoute: typeof CrmRoute
  FinanceRoute: typeof FinanceRoute
  HotelRoute: typeof HotelRoute
  HousekeepingRoute: typeof HousekeepingRoute
  HrmRoute: typeof HrmRoute
  InventoryRoute: typeof InventoryRoute
  MaintenanceRoute: typeof MaintenanceRoute
  ReservationsRoute: typeof ReservationsRoute
  RestaurantRoute: typeof RestaurantRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant': {
      id: '/restaurant'
      path: '/restaurant'
      fullPath: '/restaurant'
      preLoaderRoute: typeof RestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations': {
      id: '/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof ReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hrm': {
      id: '/hrm'
      path: '/hrm'
      fullPath: '/hrm'
      preLoaderRoute: typeof HrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/housekeeping': {
      id: '/housekeeping'
      path: '/housekeeping'
      fullPath: '/housekeeping'
      preLoaderRoute: typeof HousekeepingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel': {
      id: '/hotel'
      path: '/hotel'
      fullPath: '/hotel'
      preLoaderRoute: typeof HotelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnalyticsRoute: AnalyticsRoute,
  BillingRoute: BillingRoute,
  CrmRoute: CrmRoute,
  FinanceRoute: FinanceRoute,
  HotelRoute: HotelRoute,
  HousekeepingRoute: HousekeepingRoute,
  HrmRoute: HrmRoute,
  InventoryRoute: InventoryRoute,
  MaintenanceRoute: MaintenanceRoute,
  ReservationsRoute: ReservationsRoute,
  RestaurantRoute: RestaurantRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
